### ISSUE TITLE
好像etcd的参与没有起任何作用。

### ISSUE THREAD

**Issue by libi** [Mrfogg/gojob#1]
启动多个一样的节点，所有节点上的任务都会执行 。 所以不论某个节点是否宕机 任务都可以正常运行。也就没有分布式的意义了。

**Comment by Mrfogg** [comment]
一致性哈希算法会自动分配任务。
etcd的作用是保存的状态，只要有一个节点在运行，所有任务都可以正常执行。也就是容错机制。

**Comment by libi** [comment]
嗯， 我理解错了。我测试的时候节点name都是同一个，所以所有节点都在运行。设置不同节点的 name任务分配就正常的。

**Comment by libi** [comment]
能留一个联系方式吗。有空可以交流下

**Comment by Mrfogg** [comment]
微信号: rssq_zqypy_db
